In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df_raw = pd.read_csv('dataset.csv')

print(f'Shape awal : {df_raw.shape}')
print(f'Kolom      : {df_raw.columns.tolist()}')
print()
df_raw.head(10)

Shape awal : (8807, 12)
Kolom      : ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [105]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [106]:
df_raw.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [107]:
print('MISSING VALUES')
missing = df_raw.isna().sum()
print(pd.DataFrame({'Jumlah Missing': missing}))

print(f'\n DATA DUPLIKAT')
print(f'Jumlah baris duplikat: {df_raw.duplicated().sum()}')

print(f'\n TITLE DENGAN #')
symbol = df_raw[df_raw['title'].str.startswith('#', na=False)]['title'].unique()
print(symbol)

MISSING VALUES
              Jumlah Missing
show_id                    0
type                       0
title                      0
director                2634
cast                     825
country                  831
date_added                10
release_year               0
rating                     4
duration                   3
listed_in                  0
description                0

 DATA DUPLIKAT
Jumlah baris duplikat: 0

 TITLE DENGAN #
['#Selfie' '#Selfie 69' '#Alive' '#AnneFrank - Parallel Stories'
 '#FriendButMarried 2' '#FriendButMarried' '#blackAF' '#realityhigh'
 '#Rucker50' '#cats_the_mewvie' '#Roxy']

In [108]:
# Hapus baris missing value
df = df.dropna(how='any').reset_index(drop=True)
print(f'Setelah drop NA     : {df.shape}')

Setelah drop NA     : (5296, 16)

In [111]:
# Bersihkan title
df['title'] = df['title'].str.lstrip('#').str.title()

In [110]:
df = df[df['date_added'] != 'April 1, 2020']

In [115]:
# Konversi kolom Tanggal ke format datetime
print('Tanggal sebelum:', df['date_added'].tolist())

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce').dt.normalize()

# print('Tanggal sesudah:', df_fmt['Tanggal'].tolist())
print('Tipe data      :', df['date_added'].dtype)

# Ekstrak komponen tanggal
df['year']     = df['date_added'].dt.year
df['month']     = df['date_added'].dt.month
df['day']      = df['date_added'].dt.day
df['name_day'] = df['date_added'].dt.day_name()
df

Tanggal sebelum: [Timestamp('2021-09-24 00:00:00'), Timestamp('2021-09-24 00:00:00'), Timestamp('2021-09-24 00:00:00'), Timestamp('2021-09-23 00:00:00'), Timestamp('2021-09-21 00:00:00'), Timestamp('2021-09-20 00:00:00'), Timestamp('2021-09-19 00:00:00'), Timestamp('2021-09-19 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-16 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-15 00:00:00'), Timestamp('2021-09-14 00:00:00'), Timestamp('2021-09-10 00:00:00'), Timestamp('2021-09-10 00:00:00'), Timestamp('2021-09-09 00:00:00'), Timestamp('2021-09-08 00:00:00'), Timestamp('2021-09-07 00:00:00'), Timestamp('2021-09-05 00:00:00'), Timestamp('2021-09-04 00:00:00'), Timestamp('2021-09-02 00:00:00'), Timestamp('2021-09-02 00:00:00'), Timestamp('2021-09-02 00:00:00'), Timestamp('2021-09-02 00:00:00'), Timestamp('2021-09-02 00:00:00'), Timestamp('2021-09-02 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-09-01 00:00:00'), Timestamp('2021-08-31 00:00:00'), Timestamp('2021-08-28 00:00:00'), Timestamp('2021-08-28 00:00:00'), Timestamp('2021-08-28 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-27 00:00:00'), Timestamp('2021-08-25 00:00:00'), Timestamp('2021-08-25 00:00:00'), Timestamp('2021-08-25 00:00:00'), Timestamp('2021-08-25 00:00:00'), Timestamp('2021-08-20 00:00:00'), Timestamp('2021-08-19 00:00:00'), Timestamp('2021-08-18 00:00:00'), Timestamp('2021-08-18 00:00:00'), Timestamp('2021-08-16 00:00:00'), Timestamp('2021-08-15 00:00:00'), Timestamp('2021-08-13 00:00:00'), Timestamp('2021-08-13 00:00:00'), Timestamp('2021-08-13 00:00:00'), Timestamp('2021-08-12 00:00:00'), Timestamp('2021-08-12 00:00:00'), Timestamp('2021-08-11 00:00:00'), Timestamp('2021-08-11 00:00:00'), Timestamp('2021-08-11 00:00:00'), Timestamp('2021-08-11 00:00:00'), Timestamp('2021-08-08 00:00:00'), Timestamp('2021-08-08 00:00:00'), Timestamp('2021-08-07 00:00:00'), Timestamp('2021-08-06 00:00:00'), Timestamp('2021-08-06 00:00:00'), Timestamp('2021-08-06 00:00:00'), Timestamp('2021-08-06 00:00:00'), Timestamp('2021-08-05 00:00:00'), Timestamp('2021-08-05 00:00:00'), Timestamp('2021-08-05 00:00:00'), Timestamp('2021-08-05 00:00:00'), Timestamp('2021-08-04 00:00:00'), Timestamp('2021-08-04 00:00:00'), Timestamp('2021-08-04 00:00:00'), Timestamp('2021-08-03 00:00:00'), Timestamp('2021-08-03 00:00:00'), Timestamp('2021-08-03 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-07-30 00:00:00'), Timestamp('2021-07-29 00:00:00'), Timestamp('2021-07-28 00:00:00'), Timestamp('2021-07-28 00:00:00'), Timestamp('2021-07-27 00:00:00'), Timestamp('2021-07-27 00:00:00'), Timestamp('2021-07-24 00:00:00'), Timestamp('2021-07-23 00:00:00'), Timestamp('2021-07-23 00:00:00'), Timestamp('2021-07-22 00:00:00'), Timestamp('2021-07-22 00:00:00'), Timestamp('2021-07-22 00:00:00'), Timestamp('2021-07-21 00:00:00'), Timestamp('2021-07-20 00:00:00'), Timestamp('2021-07-19 00:00:00'), Timestamp('2021-07-17 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-16 00:00:00'), Timestamp('2021-07-15 00:00:00'), Timestamp('2021-07-15 00:00:00'), Timestamp('2021-07-14 00:00:00'), Timestamp('2021-07-13 00:00:00'), Timestamp('2021-07-10 00:00:00'), Timestamp('2021-07-09 00:00:00'), Timestamp('2021-07-08 00:00:00'), Timestamp('2021-07-08 00:00:00'), Timestamp('2021-07-08 00:00:00'), Timestamp('2021-07-08 00:00:00'), Timestamp('2021-07-07 00:00:00'), Timestamp('2021-07-07 00:00:00'), Timestamp('2021-07-07 00:00:00'), Timestamp('2021-07-07 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-07-02 00:00:00'), Timestamp('2021-07-02 00:00:00'), Timestamp('2021-07-02 00:00:00'), Timestamp('2021-07-02 00:00:00'), Timestamp('2021-07-02 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-07-01 00:00:00'), Timestamp('2021-06-30 00:00:00'), Timestamp('2021-06-30 00:00:00'), Timestamp('2021-06-28 00:00:00'), Timestamp('2021-06-26 00:00:00'), Timestamp('2021-06-25 00:00:00'), Timestamp('2021-06-25 00:00:00'), Timestamp('2021-06-24 00:00:00'), Timestamp('2021-06-22 00:00:00'), Timestamp('2021-06-22 00:00:00'), Timestamp('2021-06-21 00:00:00'), Timestamp('2021-06-21 00:00:00'), Timestamp('2021-06-21 00:00:00'), Timestamp('2021-06-19 00:00:00'), Timestamp('2021-06-19 00:00:00'), Timestamp('2021-06-18 00:00:00'), Timestamp('2021-06-18 00:00:00'), Timestamp('2021-06-17 00:00:00'), Timestamp('2021-06-17 00:00:00'), Timestamp('2021-06-17 00:00:00'), Timestamp('2021-06-17 00:00:00'), Timestamp('2021-06-16 00:00:00'), Timestamp('2021-06-16 00:00:00'), Timestamp('2021-06-16 00:00:00'), Timestamp('2021-06-15 00:00:00'), Timestamp('2021-06-15 00:00:00'), Timestamp('2021-06-15 00:00:00'), Timestamp('2021-06-15 00:00:00'), Timestamp('2021-06-15 00:00:00'), Timestamp('2021-06-13 00:00:00'), Timestamp('2021-06-13 00:00:00'), Timestamp('2021-06-11 00:00:00'), Timestamp('2021-06-11 00:00:00'), Timestamp('2021-06-11 00:00:00'), Timestamp('2021-06-11 00:00:00'), Timestamp('2021-06-10 00:00:00'), Timestamp('2021-06-10 00:00:00'), Timestamp('2021-06-10 00:00:00'), Timestamp('2021-06-10 00:00:00'), Timestamp('2021-06-10 00:00:00'), Timestamp('2021-06-09 00:00:00'), Timestamp('2021-06-09 00:00:00'), Timestamp('2021-06-09 00:00:00'), Timestamp('2021-06-07 00:00:00'), Timestamp('2021-06-05 00:00:00'), Timestamp('2021-06-05 00:00:00'), Timestamp('2021-06-04 00:00:00'), Timestamp('2021-06-04 00:00:00'), Timestamp('2021-06-04 00:00:00'), Timestamp('2021-06-04 00:00:00'), Timestamp('2021-06-04 00:00:00'), Timestamp('2021-06-03 00:00:00'), Timestamp('2021-06-03 00:00:00'), Timestamp('2021-06-03 00:00:00'), Timestamp('2021-06-03 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-06-02 00:00:00'), Timestamp('2021-05-30 00:00:00'), Timestamp('2021-05-28 00:00:00'), Timestamp('2021-05-27 00:00:00'), Timestamp('2021-05-27 00:00:00'), Timestamp('2021-05-27 00:00:00'), Timestamp('2021-05-27 00:00:00'), Timestamp('2021-05-26 00:00:00'), Timestamp('2021-05-25 00:00:00'), Timestamp('2021-05-21 00:00:00'), Timestamp('2021-05-21 00:00:00'), Timestamp('2021-05-20 00:00:00'), Timestamp('2021-05-20 00:00:00'), Timestamp('2021-05-19 00:00:00'), Timestamp('2021-05-19 00:00:00'), Timestamp('2021-05-18 00:00:00'), Timestamp('2021-05-18 00:00:00'), Timestamp('2021-05-16 00:00:00'), Timestamp('2021-05-15 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-14 00:00:00'), Timestamp('2021-05-13 00:00:00'), Timestamp('2021-05-13 00:00:00'), Timestamp('2021-05-12 00:00:00'), Timestamp('2021-05-12 00:00:00'), Timestamp('2021-05-11 00:00:00'), Timestamp('2021-05-10 00:00:00'), Timestamp('2021-05-09 00:00:00'), Timestamp('2021-05-08 00:00:00'), Timestamp('2021-05-08 00:00:00'), Timestamp('2021-05-07 00:00:00'), Timestamp('2021-05-07 00:00:00'), Timestamp('2021-05-07 00:00:00'), Timestamp('2021-05-07 00:00:00'), Timestamp('2021-05-07 00:00:00'), Timestamp('2021-05-06 00:00:00'), Timestamp('2021-05-06 00:00:00'), Timestamp('2021-05-05 00:00:00'), Timestamp('2021-05-04 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-05-01 00:00:00'), Timestamp('2021-04-30 00:00:00'), Timestamp('2021-04-30 00:00:00'), Timestamp('2021-04-28 00:00:00'), Timestamp('2021-04-27 00:00:00'), Timestamp('2021-04-27 00:00:00'), Timestamp('2021-04-27 00:00:00'), Timestamp('2021-04-27 00:00:00'), Timestamp('2021-04-24 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-23 00:00:00'), Timestamp('2021-04-22 00:00:00'), Timestamp('2021-04-22 00:00:00'), Timestamp('2021-04-21 00:00:00'), Timestamp('2021-04-21 00:00:00'), Timestamp('2021-04-19 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-17 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-16 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-15 00:00:00'), Timestamp('2021-04-14 00:00:00'), Timestamp('2021-04-14 00:00:00'), Timestamp('2021-04-14 00:00:00'), Timestamp('2021-04-12 00:00:00'), Timestamp('2021-04-10 00:00:00'), Timestamp('2021-04-09 00:00:00'), Timestamp('2021-04-09 00:00:00'), Timestamp('2021-04-09 00:00:00'), Timestamp('2021-04-09 00:00:00'), Timestamp('2021-04-09 00:00:00'), Timestamp('2021-04-08 00:00:00'), Timestamp('2021-04-05 00:00:00'), Timestamp('2021-04-04 00:00:00'), Timestamp('2021-04-04 00:00:00'), Timestamp('2021-04-03 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-04-01 00:00:00'), Timestamp('2021-03-31 00:00:00'), Timestamp('2021-03-31 00:00:00'), Timestamp('2021-03-30 00:00:00'), Timestamp('2021-03-30 00:00:00'), Timestamp('2021-03-29 00:00:00'), Timestamp('2021-03-28 00:00:00'), Timestamp('2021-03-26 00:00:00'), Timestamp('2021-03-26 00:00:00'), Timestamp('2021-03-26 00:00:00'), Timestamp('2021-03-26 00:00:00'), Timestamp('2021-03-26 00:00:00'), Timestamp('2021-03-25 00:00:00'), Timestamp('2021-03-25 00:00:00'), Timestamp('2021-03-23 00:00:00'), Timestamp('2021-03-23 00:00:00'), Timestamp('2021-03-22 00:00:00'), Timestamp('2021-03-20 00:00:00'), Timestamp('2021-03-20 00:00:00'), Timestamp('2021-03-20 00:00:00'), Timestamp('2021-03-19 00:00:00'), Timestamp('2021-03-19 00:00:00'), Timestamp('2021-03-18 00:00:00'), Timestamp('2021-03-18 00:00:00'), Timestamp('2021-03-18 00:00:00'), Timestamp('2021-03-18 00:00:00'), Timestamp('2021-03-18 00:00:00'), Timestamp('2021-03-18 00:00:00'), Timestamp('2021-03-17 00:00:00'), Timestamp('2021-03-17 00:00:00'), Timestamp('2021-03-16 00:00:00'), Timestamp('2021-03-16 00:00:00'), Timestamp('2021-03-16 00:00:00'), Timestamp('2021-03-15 00:00:00'), Timestamp('2021-03-15 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-12 00:00:00'), Timestamp('2021-03-11 00:00:00'), Timestamp('2021-03-11 00:00:00'), Timestamp('2021-03-11 00

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Tahun,Bulan,Hari,Nama_Hari,year,month,day,name_day
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021.0,9.0,24.0,Friday,2021,9,24,Friday
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021.0,9.0,24.0,Friday,2021,9,24,Friday
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021.0,9.0,24.0,Friday,2021,9,24,Friday
3,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,2021.0,9.0,23.0,Thursday,2021,9,23,Thursday
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,2021.0,9.0,21.0,Tuesday,2021,9,21,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan",2016-03-09,2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,2016.0,3.0,9.0,Wednesday,2016,3,9,Wednesday
5292,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019.0,11.0,20.0,Wednesday,2019,11,20,Wednesday
5293,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019.0,11.0,1.0,Friday,2019,11,1,Friday
5294,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0,1.0,11.0,Saturday,2020,1,11,Saturday
5295,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0,2.0,Saturday,2019,3,2,Saturday

In [116]:
print('Tipe Data')
print(df.dtypes)

Tipe Data
show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
description             object
Tahun                  float64
Bulan                  float64
Hari                   float64
Nama_Hari               object
year                     int32
month                    int32
day                      int32
name_day                object
dtype: object

In [117]:
print('=== PERBANDINGAN SEBELUM VS SESUDAH ===')
print(f'Shape awal   : {df_raw.shape}')
print(f'Shape bersih : {df.shape}')
print(f'Baris dihapus: {df_raw.shape[0] - df.shape[0]}')
print()
print('=== PREVIEW DATASET BERSIH ===')
print(df)

=== PERBANDINGAN SEBELUM VS SESUDAH ===
Shape awal   : (8807, 12)
Shape bersih : (5296, 20)
Baris dihapus: 3511

=== PREVIEW DATASET BERSIH ===
     show_id     type                          title             director  \
0         s8    Movie                        Sankofa         Haile Gerima
1         s9  TV Show  The Great British Baking Show      Andy Devonshire
2        s10    Movie                   The Starling       Theodore Melfi
3        s13    Movie                   Je Suis Karl  Christian Schwochow
4        s25    Movie                          Jeans           S. Shankar
...      ...      ...                            ...                  ...
5291   s8802    Movie                        Zinzana      Majid Al Ansari
5292   s8803    Movie                         Zodiac        David Fincher
5293   s8805    Movie                     Zombieland      Ruben Fleischer
5294   s8806    Movie                           Zoom         Peter Hewitt
5295   s8807    Movie                         Zubaan          Mozez Singh

                                                   cast  \
0     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
1     Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...
2     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
3     Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
4     Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...
...                                                 ...
5291  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
5292  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
5293  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
5294  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
5295  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                                                country date_added  \
0     United States, Ghana, Burkina Faso, United Kin... 2021-09-24
1                                        United Kingdom 2021-09-24
2                                         United States 2021-09-24
3                               Germany, Czech Republic 2021-09-23
4                                                 India 2021-09-21
...                                                 ...        ...
5291                       United Arab Emirates, Jordan 2016-03-09
5292                                      United States 2019-11-20
5293                                      United States 2019-11-01
5294                                      United States 2020-01-11
5295                                              India 2019-03-02

      release_year rating   duration  \
0             1993  TV-MA    125 min
1             2021  TV-14  9 Seasons
2             2021  PG-13    104 min
3             2021  TV-MA    127 min
4             1998  TV-14    166 min
...            ...    ...        ...
5291          2015  TV-MA     96 min
5292          2007      R    158 min
5293          2009      R     88 min
5294          2006     PG     88 min
5295          2015  TV-14    111 min

                                             listed_in  \
0     Dramas, Independent Movies, International Movies
1                         British TV Shows, Reality TV
2                                     Comedies, Dramas
3                         Dramas, International Movies
4      Comedies, International Movies, Romantic Movies
...                                                ...
5291           Dramas, International Movies, Thrillers
5292                    Cult Movies, Dramas, Thrillers
5293                           Comedies, Horror Movies
5294                Children & Family Movies, Comedies
5295    Dramas, International Movies, Music & Musicals

                                            description   Tahun  Bulan  Hari  \
0     On a photo shoot in Ghana, an American model s...  2021.0    9.0  24.0
1     A talented batch of amateur bakers face off in...  2021.0    9.0  24.0
2     A woman adjusting to life after a loss contend...  2021.0    9.0  24.0
3     After most of her family is murdered in a terr...  2021.0    9.0  23.0
4     When the father of the man she loves insists t...  2021.0    9.0  21.0
...                                                 ...     ...    ...   ...
5291  Recovering alcoholic Talal wakes up inside a s...  2016.0    3.0   9.0
5292  A political cartoonist, a crime reporter and a...  2019.0   11.0  20.0
5293  Looking to survive in a world taken over by zo...  2019.0   11.0   1.0
5294  Dragged from civilian life, a former superhero...  2020.0    1.0  11.0
5295  A scrappy but poor boy worms his way into a ty...  2019.0    3.0   2.0

      Nama_Hari  year  month  day   name_day
0        Friday  2021      9   24     Friday
1        Friday  2021      9   24     Friday
2        Friday  2021      9   24     Friday
3      Thursday  2021      9   23   Thursday
4       Tuesday  2021      9   21    Tuesday
...         ...   ...    ...  ...        ...
5291  Wednesday  2016      3    9  Wednesday
5292  Wednesday  2019     11   20  Wednesday
5293     Friday  2019     11    1     Friday
5294   Saturday  2020      1   11   Saturday
5295   Saturday  2019      3    2   Saturday

[5296 rows x 20 columns]